In [3]:
import numpy as np
def green_mean():
    """建立 [10, 20, 30, 40, 50]，回傳所有元素的平均值 (float)"""
    # TODO: 你的程式碼
    arr = np.array([10, 20, 30, 40, 50])
    
    return float(np.mean(arr))
green_mean()


30.0

In [5]:
def green_double():
    """建立 [10, 20, 30, 40, 50]，回傳所有元素乘以 2 的 ndarray"""
    # TODO: 你的程式碼
    arr = np.array([10, 20, 30, 40, 50])
    return (arr * 2)
green_double()

array([ 20,  40,  60,  80, 100])

In [6]:
def green_filter():
    """建立 [10, 20, 30, 40, 50]，回傳大於 25 的元素 (ndarray)"""
    # TODO: 你的程式碼
    arr = np.array([10, 20, 30, 40, 50])
    return (arr[arr > 25])
green_filter()

array([30, 40, 50])

In [8]:
DATA = '../datasets/ecommerce/products.csv'
prices = np.genfromtxt(DATA, delimiter=',', skip_header=1, usecols=3)  # unit_price
stocks = np.genfromtxt(DATA, delimiter=',', skip_header=1, usecols=4)  # stock_qty

def yellow_expensive_count(prices):
    """回傳單價 > 1000 的商品數量 (int)"""
    # TODO: 你的程式碼
    prices_1000 = prices[prices > 1000]
    return (f'單價大於1000的商品共有 = {prices_1000.shape[0]} 件')
yellow_expensive_count(prices)

'單價大於1000的商品共有 = 16 件'

In [9]:
def yellow_top3_stock_indices(stocks):
    """
    回傳庫存最多的前 3 個商品的索引位置 (ndarray, 由大到小排)
    提示：np.argsort
    """
    # TODO: 你的程式碼
    stocks_3 = np.argsort(stocks)
    return (f'庫存最多 = {stocks_3[0:3]} ')
yellow_top3_stock_indices(stocks)

'庫存最多 = [10  0 17] '

In [10]:
def yellow_restock_cost(prices, stocks):
    """
    單價 < 500 的商品，每種各進貨 50 個，回傳總花費 (float/int)
    提示：布林遮罩 + .sum()
    """
    # TODO: 你的程式碼
    prices_500 = prices[prices < 500]*500
    return (prices_500.sum())
yellow_restock_cost(prices, stocks)

np.float64(1203000.0)

In [11]:
def red_double11_prices(prices, stocks):
    """
    雙 11 定價規則（向量化實作）：
    - 庫存 >= 100：打 7 折
    - 庫存 20~99：打 9 折
    - 庫存 < 20：原價
    """
    # 確保輸入是 ndarray
    prices = np.array(prices)
    stocks = np.array(stocks)
    
    # 使用巢狀 np.where： np.where(條件, 若真則..., 若假則...)
    new_prices = np.where(
        stocks >= 100, 
        prices * 0.7, 
        np.where(stocks >= 20, prices * 0.9, prices)
    )
    
    return new_prices
red_double11_prices(prices, stocks)

array([1627. , 1312.5,  558. , 1202.6,  203. ,  141.3,  426.3, 1075.9,
        392.7,  766.5, 1506. , 1724.4, 1238.3,  526.4, 1677.2,  228.9,
        219.8, 1386.9, 1292.2,  267.4,  189.7, 1460.9, 1329.3,  133.7,
       1755.9, 1935. ,  700. , 1132.6,  331.8,  410.9])