"""
M1 NumPy 向量化思維 — 課後作業
================================
請完成以下每個函式，用 NumPy 向量化寫法（不要 for-loop）。
完成後 git push，GitHub Actions 會自動批改並顯示成績與解答。

提示：
- np.array, np.where, np.argsort
- 布林遮罩: arr[arr > 10]
- 統計: .sum(), .mean(), .max(), .min()
"""

# ============================================================
# 🟢 送分題（每題 10 分，共 30 分）
# ============================================================

In [2]:
import numpy as np


In [3]:

import numpy as np



def green_mean():
    """建立 [10, 20, 30, 40, 50]，回傳所有元素的平均值 (float)"""
    # TODO: 你的程式碼
    pass


def green_double():
    """建立 [10, 20, 30, 40, 50]，回傳所有元素乘以 2 的 ndarray"""
    # TODO: 你的程式碼
    pass


def green_filter():
    """建立 [10, 20, 30, 40, 50]，回傳大於 25 的元素 (ndarray)"""
    # TODO: 你的程式碼
    pass




In [4]:
import numpy as np

#def green_mean():
    #"""建立 [10, 20, 30, 40, 50]，回傳所有元素的平均值 (float)"""
    # TODO: 你的程式碼
   
arr = np.array([10, 20, 30, 40, 50])
avg_arr = np.mean(arr)
print(avg_arr)




30.0


In [5]:
#def green_double():
#"""建立 [10, 20, 30, 40, 50]，回傳所有元素乘以 2 的 ndarray"""
# TODO: 你的程式碼

arr = np.array([10, 20, 30, 40, 50])
twotimes_arr = np.multiply(arr, 2)
print(twotimes_arr)

[ 20  40  60  80 100]


In [6]:
#def green_filter():
    #"""建立 [10, 20, 30, 40, 50]，回傳大於 25 的元素 (ndarray)"""
    # TODO: 你的程式碼
arr = np.array([10, 20, 30, 40, 50])
biggerthan25_arr = arr[arr > 25]
print(biggerthan25_arr)

[30 40 50]


# ============================================================
# 🟡 核心題（每題 15 分，共 45 分）
# 以下函式會接收從 products.csv 讀出的 prices, stocks 陣列
# ============================================================

In [7]:

def yellow_expensive_count(prices):
    """回傳單價 > 1000 的商品數量 (int)"""
    # TODO: 你的程式碼
    pass


def yellow_top3_stock_indices(stocks):
    """
    回傳庫存最多的前 3 個商品的索引位置 (ndarray, 由大到小排)
    提示：np.argsort
    """
    # TODO: 你的程式碼
    pass


def yellow_restock_cost(prices, stocks):
    """
    單價 < 500 的商品，每種各進貨 50 個，回傳總花費 (float/int)
    提示：布林遮罩 + .sum()
    """
    # TODO: 你的程式碼
    pass





In [8]:
import pandas as pd
df = pd.read_csv(r"D:\python_workstation\iSpan_python-DA-cookbooks\python-da-homework-2026-main\python-da-homework-2026-main\datasets\ecommerce\products.csv")

In [9]:
import numpy as np

DATA = pd.read_csv(r"D:\python_workstation\iSpan_python-DA-cookbooks\python-da-homework-2026-main\python-da-homework-2026-main\datasets\ecommerce\products.csv")
prices = DATA.iloc[:, 3].to_numpy()
stocks = DATA.iloc[:, 4].to_numpy()
#def yellow_expensive_count(prices):
#"""回傳單價 > 1000 的商品數量 (int)"""
# TODO: 你的程式碼

prices 
prices[prices > 1000]
len(prices[prices > 1000])

16

In [10]:
import numpy as np
import pandas as pd


DATA = pd.read_csv(r"D:\python_workstation\iSpan_python-DA-cookbooks\python-da-homework-2026-main\python-da-homework-2026-main\datasets\ecommerce\products.csv")
prices = DATA.iloc[:, 3].to_numpy()
stocks = DATA.iloc[:, 4].to_numpy()

#def yellow_top3_stock_indices(stocks):
 #"""
 #回傳庫存最多的前 3 個商品的索引位置 (ndarray, 由大到小排)
 #提示：np.argsort
 #"""


stocks
np.argsort(stocks)

array([10,  0, 17, 22, 24,  5, 25,  2, 11, 13, 23,  1, 29, 20, 14, 12, 16,
       28, 21, 27, 19, 15,  4,  9, 26,  6, 18,  3,  8,  7])

In [13]:
#def yellow_restock_cost(prices, stocks):
# """
#單價 < 500 的商品，每種各進貨 50 個，回傳總花費 (float/int)
#提示：布林遮罩 + .sum()
#"""
# TODO: 你的程式碼
    
prices[prices<500] #找出單價小於500的價格
prices[prices<500] * 50 #每個商品進貨50個
sum(prices[prices<500] * 50) #總價格

np.int64(120300)

# ============================================================
# 🔴 挑戰題（25 分）
# ============================================================

In [ ]:

#def red_double11_prices(prices, stocks):
#"""
#雙 11 定價規則（必須向量化，不能用 for-loop):
#- 庫存 >= 100：打 7 折
#- 庫存 20~99：打 9 折
#- 庫存 < 20：原價
#回傳每個商品的雙 11 售價 (ndarray)
#提示：np.where 可以巢狀使用
#"""


prices_07 = prices[stocks >= 100] *0.7
prices_09 = prices[(stocks >= 20) & (stocks <= 99)] *0.9
prices_original = prices[stocks < 20]

# np.concatenate 沿指定軸連接多個陣列
total_price = np.concatenate([prices_07, prices_09, prices_original])
total_price

     
    

array([1312.5, 1202.6,  203. ,  426.3, 1075.9,  392.7,  766.5, 1238.3,
        526.4, 1677.2,  228.9,  219.8, 1292.2,  267.4,  189.7, 1460.9,
        133.7,  700. , 1132.6,  331.8,  410.9,  558. ,  141.3, 1724.4,
       1386.9, 1329.3, 1755.9, 1935. , 1627. , 1506. ])